### ISSUE TITLE
About evaluation method

### ISSUE THREAD

**Issue by Hannibal046** [yhoshi3/RaLLe#1]
Hi, Thanks for the great work. When I using the sample evaluation scripts, I got the following error. Could you please help me out?
![image](https://github.com/yhoshi3/RaLLe/assets/38466901/800359d1-f801-4de8-a605-a9a24f2b3798)

**Comment by yhoshi3** [comment]
Thank you for trying our tool and bringing the issue to our attention.
We found an error in the [evaluation config](https://github.com/yhoshi3/RaLLe/blob/main/scripts/configs/experiment_settings/sample_evaluation/nq.json), and we have now rectified it.

"e5-8b_flat" -> "flat_subset_499992"

The error you mentioned occurred because the specified retriever name in the evaluation config did not exist in the [retriever config](https://github.com/yhoshi3/RaLLe/blob/main/scripts/configs/base_settings/retrievers.json).

After the embedding process and construction of the Faiss index are complete, retrieval can be performed by correctly specifying the path to the built index in the retriever config (cf. [indexing.md](https://github.com/yhoshi3/RaLLe/blob/main/docs/indexing.md)).

If you find indexing the corpus with the e5 model to be inconvenient, you can opt for [BM25 indexing](https://github.com/yhoshi3/RaLLe/blob/main/docs/indexing.md#build-bm25-index-optional-2-minutes), which requires less time.

I hope this helps.

**Comment by Hannibal046** [comment]
Thanks for response! It now works fine!
